name: Create Types from OpenAPI Spec

on:
  push:
    branches:
      - main
    paths:
      - "openapi.yaml"
      - ".github/workflows/create-types.yml"
      - "docs/openapi/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "srcs/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install
        working-directory: ./srcs

      - name: Bundle API Docs
        run: pnpm --package=@redocly/cli dlx redocly bundle docs/openapi/openapi.yml -o public/api.yml

      - name: Generate Types from OpenAPI Spec
        run: |
          pnpx openapi-typescript ./public/api.yml --output ./srcs/shared/types/api-types.ts
            
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: generate types from OpenAPI spec'
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          signoff: false
          branch: openapi-types-update  # PR用のブランチ名（固定）
          delete-branch: true           # マージ後にブランチを削除
          title: 'chore: update generated OpenAPI types'
          body: |
            OpenAPI definitions have changed.
            This PR updates the generated TypeScript types.
            
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr
            type updates
          draft: false
