name: Create Types from OpenAPI Spec

on:
  push:
    branches:
      - main
    paths:
      - "openapi.yaml"
      - ".github/workflows/create-types.yml"
      - "docs/openapi/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "srcs/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install
        working-directory: ./srcs

      - name: Bundle API Docs
        run: pnpm --package=@redocly/cli dlx redocly bundle docs/openapi/openapi.yml -o public/api.yml

      - name: Generate Types from OpenAPI Spec
        run: |
          pnpx openapi-typescript ./public/api.yml --output ./srcs/shared/types/api-types.ts
            
      - name: Commit and Push Generated Types
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./srcs/shared/types/api-types.ts
          git commit -m 'Generate types from OpenAPI spec' || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
